### ISSUE TITLE
Scope latest event to a given service

### ISSUE THREAD

**Issue by njakobsen** [culturecode/autobiographer#10]
When refreshing feeds we look for the lastest id, but we don't scope it to a specific service so we may not be getting the correct effect if the user updates one service at a time.

**Comment by rywall** [comment]
Scope latest event to given service. Closed by 6aac1c44b4ee4d531615ee83042bfa16c3241824. Read EXIF from images. Closed by 6aac1c44b4ee4d531615ee83042bfa16c3241824. Upload progress for photos. Closed by 6aac1c44b4ee4d531615ee83042bfa16c3241824.
