### ISSUE TITLE
twitter import doesn't work

### ISSUE THREAD

**Issue by njakobsen** [culturecode/autobiographer#43]
Twitter::NotFound (GET https://api.twitter.com/1/statuses/user_timeline.json?screen_name=Nicholas%20Jakobsen: 404 Not Found: Not found):
  app/models/twitter_authentication.rb:6:in `sync_subclass_events'
  app/models/authentication.rb:33:in`sync_events'
  app/models/user.rb:17:in `sync_events'
  app/controllers/events_controller.rb:7:in`sync'

**Comment by rywall** [comment]
Closed by 33e0bb4e3e4d36065e8d
