### ISSUE TITLE
Foursquare account linking doesn't work

### ISSUE THREAD

**Issue by njakobsen** [culturecode/autobiographer#44]
ActiveRecord::StatementInvalid (PGError: ERROR:  operator does not exist: text = integer
LINE 1: ...hentication') AND ("authentications"."identifier" = 1246219)...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
: SELECT "authentications".\* FROM "authentications" WHERE ("authentications"."type" = 'FoursquareAuthentication') AND ("authentications"."identifier" = 1246219) LIMIT 1):
  app/models/authentication.rb:7:in `add_to_user'
  app/controllers/foursquare_authentications_controller.rb:17:in`create'

**Comment by rywall** [comment]
Fix identifier casting issue. Closed by fcf82b1e54b062426761efbfc4cbedb9a4e30b16.
