### ISSUE TITLE
Uploads don't work in Firefox

### ISSUE THREAD

**Issue by njakobsen** [culturecode/autobiographer#61]
The photo isn't being loaded when checking for tag details in the photos_controller

**Comment by rywall** [comment]
it seems like the problem is firefox doesn't set the content type correctly which causes exifr to choke.

**Comment by rywall** [comment]
it's actually because plupload stripped the exif info on resize (but only firefox does the resize). the new version fixes this.

**Comment by rywall** [comment]
Update plupload to fix exif stripping issue. Closed by 4124b5d96729a93032a24a7ee2e4e97351f490e6.
