### ISSUE TITLE
Cache isn't cleared when new photo is added to photo group

### ISSUE THREAD

**Issue by rywall** [culturecode/autobiographer#66]
this might only be for duplicate photos?

**Comment by njakobsen** [comment]
Fixed photo group caching problem. Closed by aecf2d21899dc6c91f660a7fb3828583fd296024. Fixed bug in chapter ordering that caused chapters to ignore the offset when ordering. Chapters numbers once again update when a new chapter is inserted. Added a fake placeholder script so browsers that don&#39;t support the placeholder attribute still get the hints. Closed by aecf2d21899dc6c91f660a7fb3828583fd296024.
