### ISSUE TITLE
Handle photos without any exif data

### ISSUE THREAD

**Issue by rywall** [culturecode/autobiographer#9]
Don't blow up. Make a new photo group at Time.now and put them in there, then make a note that explains why they're there and that in the future the user will be able to move them to the appropriate spot.

**Comment by njakobsen** [comment]
Then maybe later, allow user to specify when they were taken

**Comment by njakobsen** [comment]
Changed slogan. Images without datestamps now appear at the end of the timeline. Closed by 151fb8a4092e22e3b15a322ff5869f4aaa380576.
